### ISSUE TITLE
Changes to Main Page

### ISSUE THREAD

**Issue by salman-bhai** [IEEE-NITK/ieee-nitk.github.io#258]
Remove `We are now Recruiting` message from the Website Main Page as it is leading to a closed Google Form

**Comment by rohit-mp** [comment]
There's a link in the main page and in `joinus.html` which is over a year old.
The link over there should definitely be removed but should the page stay up? Or do we take down that page entirely and put it up only during recruitments?
And instead of putting the form in the main page, we should probably just put it in `/joinus` and put a much bigger hyperlink in the mainpage during recruitment season. What do you think?

**Comment by salman-bhai** [comment]
Let's just put a page and use a message called recruitments closed for this year. Apply next year.

**Comment by rohit-mp** [comment]
Removing the message from homepage and adding the recruitments over message in the `joinus` page seems better. Will create a pr for the same.
